#pragma once


enum class NotifyType {
  PULSER_RCVR_DISCOVERED = 0,
  CURRENT_PULSER_RCVR_CHANGED = 1,
  PULSER_RCVR_DETACH = 2,
  DISCOVERY_STARTED = 3,
  DISCOVERY_COMPLETE = 4,
  PROPERTY_CHANGE = 5,
  STATE_CHANGE = 6,
  ERROR = 7,
};
