name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2025
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
      - name: Build x64 dynamic library
        run: msbuild ${{github.workspace}}\JSR-SDK.vcxproj -t:Rebuild -p:Configuration=dynamic -p:Platform=x64
      - name: Build x86 dynamic library
        run: msbuild ${{github.workspace}}\JSR-SDK.vcxproj -t:Rebuild -p:Configuration=dynamic -p:Platform=Win32
      - name: Build x64 static library
        run: msbuild ${{github.workspace}}\JSR-SDK.vcxproj -t:Rebuild -p:Configuration=static -p:Platform=x64
      - name: Build x86 static library
        run: msbuild ${{github.workspace}}\JSR-SDK.vcxproj -t:Rebuild -p:Configuration=static -p:Platform=Win32
      - name: Write version to file
        shell: pwsh
        run: Set-Content -Path "${{github.workspace}}\VERSION" -Value "${{github.ref_name}}" -Encoding ASCII
      - name: Zip release
        shell: pwsh
        run: Compress-Archive -Path '${{github.workspace}}\include','${{github.workspace}}\lib', '${{github.workspace}}\CMakeLists.txt', '${{github.workspace}}\LICENSE', '${{github.workspace}}\VERSION' -DestinationPath '${{github.workspace}}\JSR-SDK-${{ github.ref_name }}.zip' -Force
      - name: Generate hash
        shell: pwsh
        run: |
            $hash = (Get-FileHash -Path ${{github.workspace}}\JSR-SDK-${{ github.ref_name }}.zip -Algorithm SHA256).Hash
            $hash | Out-File -Encoding ascii "${{github.workspace}}\JSR-SDK-${{ github.ref_name }}.zip.sha256"
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          files: |
            ${{github.workspace}}\JSR-SDK-${{ github.ref_name }}.zip
            ${{github.workspace}}\JSR-SDK-${{ github.ref_name }}.zip.sha256
             
